# Generated by Django 2.2.2 on 2019-06-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functionalityName', models.CharField(max_length=100)),
                ('functionalityType', models.CharField(choices=[('EE', 'EE'), ('CE', 'CE'), ('SE', 'SE')], max_length=2)),
                ('qtdALR', models.PositiveIntegerField()),
                ('qtdDER', models.PositiveIntegerField()),
                ('functionComplexity', models.CharField(max_length=5)),
                ('qtdFunctionPts', models.PositiveIntegerField()),
                ('countName', models.CharField(max_length=100)),
                ('registrationDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
