# Generated by Django 2.2.2 on 2019-06-06 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionalFunction', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionFunction',
            new_name='TransactionalFunction',
        ),
    ]
